version: '3.4'

services:
  eshopmicro_catalog_db:
    image: mongo

  eshopmicro_basket_db:
    image: redis:alpine

  eshopmicro_discount_db:
    image: postgres

  eshopmicro_order_db:
    image: mcr.microsoft.com/mssql/server
  
  eshopmicro_rabbitmq:
    image: rabbitmq:management-alpine
  
  eshopmicro_mongoclient:
    image: mongoclient/mongoclient

  eshopmicro_pgadmin:
    image: dpage/pgadmin4
  
  eshopmicro_portainer:
    image: portainer/portainer-ce

  eshopmicro_catalog_api:
    image: ${DOCKER_REGISTRY-}eshopmicrocatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/EShopMicro.Catalog.API/Dockerfile

  eshopmicro_basket_api:
    image: ${DOCKER_REGISTRY-}eshopmicrobasketapi
    build:
      context: .
      dockerfile: Services/Basket/EShopMicro.Basket.API/Dockerfile

  eshopmicro_discount_api:
    image: ${DOCKER_REGISTRY-}eshopmicrodiscountapi
    build:
      context: .
      dockerfile: Services/Discount/EShopMicro.Discount.API/Dockerfile

  eshopmicro_discount_grpc:
    image: ${DOCKER_REGISTRY-}eshopmicrodiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/EShopMicro.Discount.Grpc/Dockerfile

  eshopmicro_ordering_api:
    image: ${DOCKER_REGISTRY-}eshopmicroorderingapi
    build:
      context: .
      dockerfile: Services/Ordering/EShopMicro.Ordering.API/Dockerfile

  eshopmicro_ocelotapigateway:
    image: ${DOCKER_REGISTRY-}eshopmicroocelotapigateway
    build:
      context: .
      dockerfile: APIGateways/EShopMicro.OcelotAPIGateway/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  





