version: '3.4'

services:

  eshopmicro_catalog_db:
    container_name: eshopmicro_catalog_db  
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db      

  eshopmicro_basket_db:
    container_name: eshopmicro_basket_db
    restart: always
    ports: 
      - "6379:6379"



  eshopmicro_catalog_api:
    container_name: eshopmicro_catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://eshopmicro_catalog_db:27017"
    depends_on:
      - eshopmicro_catalog_db
    ports:
      - "19010:80"

  eshopmicro_basket_api:
    container_name: eshopmicro_basket_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=eshopmicro_basket_db:6379"
    depends_on:
      - eshopmicro_basket_db
    ports:
      - "19011:80"


  eshopmicro_portainer:
    container_name: eshopmicro_portainer
    restart: always
    ports: 
      - "18000:8000"
      - "19000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

