version: '3.4'

services:
  eshopmicro_catalog_db:
    image: mongo

  eshopmicro_basket_db:
    image: redis:alpine
  
  eshopmicro_portainer:
    image: portainer/portainer-ce

  eshopmicro_catalog_api:
    image: ${DOCKER_REGISTRY-}eshopmicrocatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/EShopMicro.Catalog.API/Dockerfile

  eshopmicro_basket_api:
    image: ${DOCKER_REGISTRY-}eshopmicrobasketapi
    build:
      context: .
      dockerfile: Services/Basket/EShopMicro.Basket.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  

