version: '3.4'

services:
  eshopmicro_catalog_db:
    container_name: eshopmicro_catalog_db  
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db      

  eshopmicro_catalog_api:
    container_name: eshopmicro_catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://eshopmicro_catalog_db:27017"
    depends_on:
      - eshopmicro_catalog_db
    ports:
      - "19000:80"
