version: '3.4'

services:

  eshopmicro_catalog_db:
    container_name: eshopmicro_catalog_db  
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db      

  eshopmicro_basket_db:
    container_name: eshopmicro_basket_db
    restart: always
    ports: 
      - "6379:6379"

  eshopmicro_discount_db:
    container_name: eshopmicro_discount_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports: 
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
  
  eshopmicro_order_db:
    container_name: eshopmicro_order_db
    environment:
        SA_PASSWORD: "System123!"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "2433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets

  
  eshopmicro_pgadmin:
    container_name: eshopmicro_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "15050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  eshopmicro_portainer:
    container_name: eshopmicro_portainer
    restart: always
    ports: 
      - "18000:8000"
      - "19000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  eshopmicro_catalog_api:
    container_name: eshopmicro_catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://eshopmicro_catalog_db:27017"
    depends_on:
      - eshopmicro_catalog_db
    ports:
      - "19010:80"

  eshopmicro_basket_api:
    container_name: eshopmicro_basket_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=eshopmicro_basket_db:6379"
      - "GrpcSettings:DiscountUrl=http://eshopmicro_discount_grpc"
    depends_on:
      - eshopmicro_basket_db
    ports:
      - "19011:80"

  eshopmicro_discount_api:
    container_name: eshopmicro_discount_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=eshopmicro_discount_db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234" 
    depends_on:
      - eshopmicro_discount_db
    ports:
      - "19012:80"


  eshopmicro_discount_grpc:
    container_name: eshopmicro_discount_grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=eshopmicro_discount_db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234"        
    depends_on:
      - eshopmicro_discount_db
    ports:
      - "19013:80"      
   

  eshopmicro_ordering_api:
    container_name: eshopmicro_ordering_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=eshopmicro_order_db;Database=EShopMicro.Ordering;User Id=sa;Password=System123!;TrustServerCertificate=true" 
    depends_on:
      - eshopmicro_order_db
    ports:
      - "19014:80"

